CREATE TABLE CITY (
    ID NUMBER NOT NULL,
    NAME VARCHAR2(17) NOT NULL,
    COUNTRYCODE VARCHAR2(3) NOT NULL,
    DISTRICT VARCHAR2(20) NOT NULL,
    POPULATION NUMBER NOT NULL
);
CREATE TABLE COUNTRY (
    CODE VARCHAR2(3) NOT NULL,
    NAME VARCHAR2(52) NOT NULL,
    CONTINENT VARCHAR2(13) NOT NULL,
    REGION VARCHAR2(26) NOT NULL,
    SURFACEAREA NUMBER NOT NULL,
    INDUSTRYSUMMARY VARCHAR2(50) NOT NULL,
    POPULATION NUMBER NOT NULL,
    LIFEEXPECTANCY NUMBER NOT NULL,
    GNP NUMBER NOT NULL,
    GNPOLD VARCHAR2(9)  NOT NULL,
    LOCALNAME VARCHAR2(45) NOT NULL,
    GOVERNMENTFORM VARCHAR2(45) NOT NULL,
    HEADOFSTATE VARCHAR2(60) NOT NULL,
    CAPITAL NUMBER NOT NULL,
    CODE2 VARCHAR2(2) NOT NULL
);

-- Note: CITY.CountryCode and COUNTRY.Code
SELECT SUM(CITY.POPULATION)
FROM CITY
INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Asia';
